### ISSUE TITLE
More configuration

### ISSUE THREAD

**Issue by eastehr** [espruino/EspruinoHub#23]
Good morning Gordon, 

thank you for a brilliant library!. However, I am wondering if one can do more configuration: 
a) Add an external Broker (instead of localhost)
b) Influence the topics (at least prefix-wise) and potentially the amount of data sent

And lastly I would like to understand whether the system restarts itself / How and where I can debug it. I implemented your logic for a button press (http://forum.espruino.com/conversations/299127/) and some logic that the Puck.js blinks on a certain MQTT topic. I understand that the two parts are exclusive (either scanning for an advertisement or connecting / sending). However, it works at startup but at some point in time seems to stop working. 

Architecture: Using a Raspberry Pi 3B running MQTT on localhost. Running a Python script which translates the most relevant messages (RSSI every minute, commands, button presses) from the localhost MQTT to other, different topics on localhost (in future this will be an external MQTT). So basically bridging the localhost MQTT to a public MQTT for certain commands. The problems seem to occur mostly when I init the above logic on boot, when I start manually it seems slightly more reliable. I am used to Java application level, but a rookie for BLE/Python/Javascript.

**Comment by gfwilliams** [comment]
Hi! I think you can set up the external broker pretty easily already - just change the config file here: https://github.com/espruino/EspruinoHub/blob/master/config.json#L37

I'm definitely up for making the prefix configurable - what sort of thing did you have in mind - changing '/ble/advertise'? What sort of settings would you want that would influence the amount of data? Some flags for the kind of advertising events that got broadcast?

As far as restarting, this might help? https://github.com/espruino/EspruinoHub/blob/master/config.json#L12

It restarts itself if it doesn't see any BLE advertisements for a while (since sometimes Noble gets confused). If that doesn't fix it for you, you could manually do a `/etc/init.d/bluetooth restart` and see if that helps. If it does, it might be possible to add that to the code somehow.

**Comment by eastehr** [comment]
Thanks for the fast answer. Regarding the topics: 
I would at least provide a customized prefix to /ble/..... 
In terms of the configuration: E.g. I could imagine to limit it to the history (controlled by config-flags): 
- Ideally one could whitelist services as such: 
{
      "RSSI" : "10s" // send only every 10 seconds, even if more data was posted
      "Temperature": "1h" // Or the equivalent Advertisement characteristic
      "*" : "1h" // Anything else every hour...
} 
Or maybe even better with a "onChange" and a tolerance (obviously only for numeric values). 
If that is complicated, one could also just say: "Send all data only every N seconds" --> Collect the data for each object ongoing, but post it to MQTT only every N seconds. That would effectively limit the number of data on MQTT. 

Of course this are just some ideas which I feel would make the library more flexible. As I understand (I only have Puck.js at the moment) I could "program" nearly all devices by writing/reading data to BLE, right?

**Comment by kun-bo** [comment]
hello,Gordon!thank you!
I connect to a device using MQTT packets like this: /ble/read/f9:95:b6:f8:bf:e0/180a/2a29
the raspberrypi Prints the following information:
<Discover> Starting scan...
<Discover> Scanning started.
<History> New History Topic for /ble/presence/19:7e:de:53:85:31
<History> New History Topic for /ble/advertise/19:7e:de:53:85:31/rssi
<History> New History Topic for /ble/presence/78:82:d1:7d:44:b5
<History> New History Topic for /ble/advertise/78:82:d1:7d:44:b5/rssi
<History> New History Topic for /ble/presence/f9:95:b6:f8:bf:e0
<History> New History Topic for /ble/advertise/f9:95:b6:f8:bf:e0/rssi
<Discover> Scanning stopped.
<Connect> f9:95:b6:f8:bf:e0: Connecting...
<Connect> Connected.
<Connect> f9:95:b6:f8:bf:e0: Getting Service...
<Connect> f9:95:b6:f8:bf:e0: found service: 180a
<Connect> f9:95:b6:f8:bf:e0: found characteristic: 2a29
<Connect> f9:95:b6:f8:bf:e0: Read.
<Connect> f9:95:b6:f8:bf:e0: Disconnecting due to lack of use (after 10 secs)
<Connect> f9:95:b6:f8:bf:e0: Disconnecting.
<Connect> f9:95:b6:f8:bf:e0: Disconnected
my question  : 1.where is the value of the Read,how can i get it ?
2.how can i modify the time  -->(after 10 secs)? Would it have any other effect to modify it?

**Comment by gfwilliams** [comment]
Hi - there's some info here: https://github.com/espruino/EspruinoHub#mqtt-bridge

A read on `/ble/read/DEVICE/SERVICE/CHARACTERISTIC` sends the data back as `/ble/data/DEVICE/SERVICE/CHARACTERISTIC`

To change the connection timeout you'd have to modify https://github.com/espruino/EspruinoHub/blob/master/lib/connect.js#L20

**However** if you want to stay connected for longer, just send the topic `/ble/ping/DEVICE` every 5 seconds or so and it'll cause the connection to be kept open. That's the easiest solution

**Comment by kun-bo** [comment]
thanks for your help,Gordon! the problem has been solved ,
/ble/notify/DEVICE/SERVICE/CHARACTERISTIC connects and starts notifications on the characteristic, which send data back on /ble/data/DEVICE/SERVICE/CHARACTERISTIC
it doesn't return a valle with zhe method above,the raspberrypi Prints the following information:
window 1:MQTT

<Discover> Restarting scan
<Discover> Scanning started.
<Discover> Scanning stopped.
<Connect> f9:95:b6:f8:bf:e0: Connecting...
<Connect> Connected.
<Connect> f9:95:b6:f8:bf:e0: Getting Service...
<Connect> f9:95:b6:f8:bf:e0: found service: 180d
<Connect> f9:95:b6:f8:bf:e0: found characteristic: 2a37
<Connect> f9:95:b6:f8:bf:e0: Read.
<Connect> f9:95:b6:f8:bf:e0: Disconnecting due to lack of use (after 10 secs)
<Connect> f9:95:b6:f8:bf:e0: Disconnecting.
<Connect> f9:95:b6:f8:bf:e0: Disconnected
<Discover> Restarting scan
<Discover> Scanning started.
<Discover> Scanning stopped.
<Connect> f9:95:b6:f8:bf:e0: Connecting...
<Connect> Connected.
<Connect> f9:95:b6:f8:bf:e0: Getting Service...
<Connect> f9:95:b6:f8:bf:e0: found service: 180d
<Connect> f9:95:b6:f8:bf:e0: found characteristic: 2a37
<Connect> f9:95:b6:f8:bf:e0: startNotifications complete
<Connect> f9:95:b6:f8:bf:e0: Disconnecting due to lack of use (after 10 secs)
<Connect> f9:95:b6:f8:bf:e0: Disconnecting.
<Connect> f9:95:b6:f8:bf:e0: Disconnected
window 2:mosquitto_pub
pi@raspberrypi:~ $ mosquitto_pub -h localhost -t /ble/read/f9:95:b6:f8:bf:e0/180d/2a37 -m "  "
pi@raspberrypi:~ $ mosquitto_pub -h localhost -t /ble/notify/f9:95:b6:f8:bf:e0/180d/2a37 -m "  "
window 3:mosquitto_sub
pi@raspberrypi:~ $ mosquitto_sub -h localhost -t "/ble/data/f9:95:b6:f8:bf:e0/180d/2a37" 


this Service can be read,write and nofify ,it retuns  a value by reading,but notify not.
how can i get the value of notify ?

**Comment by gfwilliams** [comment]
I'm not sure I understand... As long as you send `/ble/notify/f9:95:b6:f8:bf:e0/180d/2a37` then whenever the device notifies of a change, the data will be sent on `/ble/data/f9:95:b6:f8:bf:e0/180d/2a37`

... but if the device doesn't send any data via notify, you won't get anything on `/ble/data/f9:95:b6:f8:bf:e0/180d/2a37`

**Comment by kun-bo** [comment]
thanks for your help,Gordon! ,
# Test publish
mosquitto_pub -h localhost -t  /ble/read/DEVICE/SERVICE/CHARACTERISTIC  -m "Hello world"
mosquitto_sub -h localhost -t "/ble/read/DEVICE/SERVICE/CHARACTERISTIC"
mosquitto_sub -h localhost -t "/ble/data/DEVICE/SERVICE/CHARACTERISTIC"
The above command,the data and returned data for display are string, how can i use it for HEX ?

**Comment by gfwilliams** [comment]
It's worth noting that in your example you should really `mosquitto_sub` **before** you send the read, so you're sure you don't miss it.

Getting hex is just a general MQTT question I think. Just search for it: https://mosquitto.org/man/mosquitto_sub-1.html

For instance that says:

```
Specify the output format as "ISO-8601 date : topic : payload in hex"

mosquitto_sub -F '@Y-@m-@dT@H:@M:@S@z : %t : %x' -t '#'

```
