### ISSUE TITLE
Subscribe from other broker - Home Assistant

### ISSUE THREAD

**Issue by wpmjones** [espruino/EspruinoHub#27]
I'm a novice at best, so if I'm asking poor questions, I apologize.  I got EspruinoHub up and running in a Raspberry Pi Zero W today.  It is recognizing bluetooth devices and I can view the http site to track status, etc.  I have two questions.

1) My goal is to connect this to my Home Assistant instance (separate computer that has its own mqtt broker) to track presence of specific devices.  I just want to make sure that I understand what EspruinoHub is doing "out of the box".  Is it publishing topics (ble/presence/DEVICE) to the broker specified in the config.json?

2) How are you handling bluetooth devices that advertise spoofed mac addresses (for security)?  If I hard code the correct mac address in config.json, will EspruinoHub look specifically for that device or only apply the name when it receives something from that mac address?  I ask because your examples confused me.  I expected the known devices in config.json to be something more along the lines of "jims_phone", "sallys_tablet", not specific rooms where the Pi is located.

Again, sorry for the basic questions.  I just need to determine next steps now that EspruinoHub is up and running.  I'm brand new to ble and mqtt.

**Comment by gfwilliams** [comment]
No problem....

> Is it publishing topics (ble/presence/DEVICE) to the broker specified in the config.json?

Yes, that's correct.

> How are you handling bluetooth devices that advertise spoofed mac addresses (for security)?

We're not. Basically anyone can spoof advertising packets - if you want security you'll probably want to put some secret key in each device and 'sign' the advertisement - but that's something you would have to do yourself.

> If I hard code the correct mac address in config.json,

It'll only apply the name when it receives advertisements from that mac address

Although if you mention that for a BLE write it'll attempt to connect to that mac address - but because of BLE it'll silently fail if there are no advertisements - it won't broadcast the MAC address.

>  I expected the known devices in config.json to be something more along the lines of "jims_phone", "sallys_tablet", not specific rooms where the Pi is located.

It's because in my setup, I have temperature sensors in those rooms, with one, global Pi. I can see that could get confusing though.

Just FYI - currently there's no real handling for multiple Pis running EspruinoHub - for that to work you'd need to at the very least use a different prefix (which isn't a confif option yet) - eg `/bleupstairs/` and `/bleupstairs/`

**Comment by gfwilliams** [comment]
If you have questions like this in the future, could you ask on the forum though? http://forum.espruino.com

I have 2000+ issues filed on GitHub (the majority fixed) - and it's just much easier to have questions on the forum with GitHub issues for actual problems in the code.
