### ISSUE TITLE
Retain topic /ble/presence

### ISSUE THREAD

**Issue by pavoroby** [espruino/EspruinoHub#46]
Hi. 
How I can save the state and contents of the "presence" topic?

**Comment by gfwilliams** [comment]
You mean so that as soon as you connect to MQTT you can get the last value?

I guess it might make sense to modify EspruinoHub to make that particular publish command with retain? It's easy enough to tweak it - it gets called at https://github.com/espruino/EspruinoHub/blob/1f7f8e2ec2402dbe7b123603cfdda1a15f994b51/lib/discovery.js#L81

**Comment by pavoroby** [comment]
Yes, that’s exactly what I want. Keep status in my MKTT broker constantly.

Tell me what exactly should I fix in "EspruinoHub/lib/discovery.js"? My file looks exactly like you sent "mqtt.send(config.mqtt_prefix+"/presence/"+id, "1"); "

**Comment by pavoroby** [comment]
mqtt.send(config.mqtt_prefix+"/presence/"+id, "0"); 
-- It's right?

**Comment by gfwilliams** [comment]
Just fixed this for you myself

**Comment by pavoroby** [comment]
Perfect!
